version: '3.3'

volumes:
  postgres_volume:

services:
  postgres-link-shortener:
    image: postgres:latest
    container_name: postgres-ls
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: mentoring
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: Ab123456
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  link-shortener:
    depends_on:
      - postgres-link-shortener
    build: .
    container_name: link-shortener
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose